#!/usr/bin/env python3
"""Generate docs/history/index.md: champions and the record book.

Champions are the top finishers of each season's standings. Records are whatever
is computable from the current data (standings-based now; score-based once games
with scores are added). Nothing here is hand-maintained.

    .venv/bin/python scripts/generate_history.py
"""

from pathlib import Path

from lib.data import load_franchises, load_seasons
from lib.standings import get_standings
from lib.records import compute_records

ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = ROOT / "docs" / "history" / "index.md"

GENERATED_NOTE = "<!-- GENERATED by scripts/generate_history.py — do not edit by hand. -->"


def champions_table(seasons, franchises):
    lines = [
        "| Season | Champion | Runner-Up | Third | Champion Record |",
        "|---|---|---|---|---|",
    ]
    for season in seasons:
        by_finish = {r["finish"]: r for r in get_standings(season, franchises)}
        champ = by_finish.get(1)
        runner = by_finish.get(2)
        third = by_finish.get(3)
        lines.append(
            f"| {season['season']} "
            f"| {champ['name'] if champ else '—'} "
            f"| {runner['name'] if runner else '—'} "
            f"| {third['name'] if third else '—'} "
            f"| {champ['record'] if champ else '—'} |"
        )
    return "\n".join(lines)


def records_table(seasons, franchises):
    lines = [
        "| Category | Holder | Value | Season |",
        "|---|---|---|---|",
    ]
    for r in compute_records(seasons, franchises):
        season = r["season"] if r["season"] is not None else "—"
        lines.append(f"| {r['category']} | {r['holder']} | {r['value']} | {season} |")
    return "\n".join(lines)


def main():
    franchises = load_franchises()
    seasons = load_seasons()

    content = f"""---
layout: page
title: League History
permalink: /history/
---
{GENERATED_NOTE}

## Champions

{champions_table(seasons, franchises)}

## Record Book

{records_table(seasons, franchises)}

*More records (highest-scoring week, biggest blowouts, head-to-head) unlock once
seasons have game-by-game scores added.*
"""

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content)
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
