#!/usr/bin/env python3
"""Generate the owner pages:

  docs/teams/index.md      - every owner, sortable-ish summary table
  docs/teams/<id>.md       - one page per owner: trophy case, season-by-season,
                             all-time record, head-to-head vs everyone

    .venv/bin/python scripts/generate_teams.py
"""

from pathlib import Path

from lib.data import load_franchises, load_seasons
from lib.teams import compute_profiles, win_pct, rec_str, fmt_titles, split_titles
from lib.rulings import load_overrides
from lib.render import heat_chip, winpct_chip, finish_tag

ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = ROOT / "docs" / "teams"

GEN = "<!-- GENERATED by scripts/generate_teams.py — do not edit by hand. -->"


def ordinal(n):
    if n is None:
        return "—"
    suffix = "th" if 10 <= n % 100 <= 20 else {1: "st", 2: "nd", 3: "rd"}.get(n % 10, "th")
    return f"{n}{suffix}"


def pct(x):
    return f"{x:.3f}".lstrip("0") or ".000"


def best_finish_label(p):
    """Best finish with the year(s): 'Shiva (2014, 2017)', 'Co-champ (2016)',
    or '2nd (2023)'."""
    outright, co = split_titles(p["champ_years"])
    if outright:
        yrs = ", ".join(str(y) for y in outright)
        return f'<span class="shiva">Shiva</span> ({yrs})'
    if co:
        yrs = ", ".join(str(y) for y in co)
        return f'<span class="shiva">Co-champ</span> ({yrs})'
    best = p["best_finish"]
    yrs = ", ".join(str(y) for y in sorted(s["year"] for s in p["seasons"] if s["finish"] == best))
    return f"{ordinal(best)} ({yrs})"


def sorted_profiles(profiles):
    return sorted(
        profiles.values(),
        key=lambda p: (p["titles"], p["reg"]["win_pct"], p["reg"]["w"]),
        reverse=True,
    )


def index_page(profiles):
    lines = [
        "---", "layout: page", "title: Owners", "permalink: /teams/", "---", GEN,
        "",
        "Every manager in league history. Click a name for their full profile.",
        "",
        "| Owner | Seasons | All-Time Record | Win% | Titles | Sackos | Best Finish |",
        "|:--|--:|:--|--:|--:|--:|:--|",
    ]
    for p in sorted_profiles(profiles):
        reg = p["reg"]
        link = f"[{p['name']}]({{{{ '/teams/{p['id']}/' | relative_url }}}})"
        lines.append(
            f"| {link} | {p['seasons_count']} | {rec_str(reg['w'], reg['l'], reg['t'])} "
            f"| {winpct_chip(reg['win_pct'], pct(reg['win_pct']))} "
            f"| {fmt_titles(p['titles'])} | {p['sackos'] or ''} | {best_finish_label(p)} |"
        )
    return "\n".join(lines) + "\n"


def honors(p):
    """Inline honors summary: Shivas, co-championships, runner-ups, thirds,
    Sackos, playoff berths."""
    bits = []
    outright, co = split_titles(p["champ_years"])
    if outright:
        bits.append(f"🏆 <b>{len(outright)}× Shiva</b> ({', '.join(str(y) for y in outright)})")
    if co:
        bits.append(f"🤝 <b>Co-champ</b> ({', '.join(str(y) for y in co)})")
    if p["runner_ups"]:
        bits.append(f"🥈 {p['runner_ups']}× Runner-Up")
    if p["thirds"]:
        bits.append(f"🥉 {p['thirds']}× Third")
    if p["sackos"]:
        yrs = ", ".join(str(y) for y in sorted(p["sacko_years"]))
        bits.append(f'💩 <b>{p["sackos"]}× Sacko</b> ({yrs})')
    if p["berths"]:
        bits.append(f"{p['berths']}× Playoffs")
    return " · ".join(bits) if bits else "No hardware yet."


def tile(label, value):
    return (f'<div class="tile"><div class="tile__label">{label}</div>'
            f'<div class="tile__val">{value}</div></div>')


def resume_card(p):
    reg = p["reg"]
    pl = p["playoff"]
    playoff_line = rec_str(pl["w"], pl["l"], pl["t"]) if (pl["w"] + pl["l"] + pl["t"]) else "—"
    tiles = "".join([
        tile("All-Time", f"{rec_str(reg['w'], reg['l'], reg['t'])} <span class='muted'>({pct(reg['win_pct'])})</span>"),
        tile("Titles", fmt_titles(p["titles"])),
        tile("Sackos", p["sackos"]),
        tile("Playoffs", playoff_line),
        tile("Seasons", p["seasons_count"]),
        tile("Best Finish", best_finish_label(p)),
    ])
    return (f'<div class="resume">\n'
            f'  <div class="resume__honors">{honors(p)}</div>\n'
            f'  <div class="resume__grid">{tiles}</div>\n'
            f'</div>')


def season_table(p):
    lines = [
        "| Season | Team | Finish | Record | PF | PA |",
        "|:--|:--|:--|:--|--:|--:|",
    ]
    pfs = [s["pf"] for s in p["seasons"] if s["pf"] is not None]
    lo, hi = (min(pfs), max(pfs)) if pfs else (0, 0)
    for s in p["seasons"]:
        pf = heat_chip(s["pf"], lo, hi) if s["pf"] is not None else "—"
        pa = s["pa"] if s["pa"] is not None else "—"
        team = s["team"] + finish_tag(s["finish"], s["team_count"], s["is_co"])
        lines.append(
            f"| {s['year']} | {team} | {ordinal(s['finish'])} | {s['record']} | {pf} | {pa} |"
        )
    return "\n".join(lines)


def h2h_table(p, profiles):
    opps = [(oid, r) for oid, r in p["h2h"].items() if oid in profiles]
    opps.sort(key=lambda kv: profiles[kv[0]]["short"].lower())
    lines = [
        "| Opponent | Record | Win% | Avg PF | Avg PA |",
        "|:--|:--|--:|--:|--:|",
    ]
    for oid, r in opps:
        games = r["w"] + r["l"] + r["t"]
        opp = profiles[oid]
        link = f"[{opp['short']}]({{{{ '/teams/{oid}/' | relative_url }}}})"
        wp = win_pct(r["w"], r["l"], r["t"])
        lines.append(
            f"| {link} | {rec_str(r['w'], r['l'], r['t'])} | {winpct_chip(wp, pct(wp))} "
            f"| {r['pf'] / games:.1f} | {r['pa'] / games:.1f} |"
        )
    return "\n".join(lines)


def owner_page(p, profiles):
    latest_team = p["seasons"][0]["team"] if p["seasons"] else ""
    return f"""---
layout: page
title: {p['name']}
permalink: /teams/{p['id']}/
---
{GEN}

[← All owners]({{{{ '/teams/' | relative_url }}}})

<p class="owner-sub">Most recent: {latest_team}</p>

{resume_card(p)}

## Season by season

{season_table(p)}

## Head-to-head

{h2h_table(p, profiles)}
"""


def main():
    franchises = load_franchises()
    seasons = load_seasons()
    overrides = load_overrides()
    profiles = compute_profiles(seasons, franchises, overrides)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "index.md").write_text(index_page(profiles))
    for p in profiles.values():
        (OUT_DIR / f"{p['id']}.md").write_text(owner_page(p, profiles))

    print(f"Wrote docs/teams/index.md and {len(profiles)} owner pages")


if __name__ == "__main__":
    main()
