#!/usr/bin/env python3
"""Generate docs/history/index.md: champions and the record book.

Champions are the top finishers of each season's standings. Records are whatever
is computable from the current data (standings-based now; score-based once games
with scores are added). Nothing here is hand-maintained.

    .venv/bin/python scripts/generate_history.py
"""

from pathlib import Path

from lib.data import load_franchises, load_seasons, owner_link
from lib.standings import get_standings
from lib.records import compute_records
from lib.rulings import load_overrides, co_champions

ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = ROOT / "docs" / "history" / "index.md"

GENERATED_NOTE = "<!-- GENERATED by scripts/generate_history.py — do not edit by hand. -->"


def champions_table(seasons, franchises, overrides):
    lines = [
        "| Season | Champion | Runner-Up | Third | Champion Record |",
        "|---|---|---|---|---|",
    ]
    for season in seasons:
        rows = {r["id"]: r for r in get_standings(season, franchises)}
        by_finish = {r["finish"]: r for r in rows.values()}

        def cell(r):
            return owner_link(r["id"], r["name"], franchises) if r else "—"

        co = co_champions(season["season"], overrides)
        if co:
            champ_cell = " & ".join(owner_link(fid, rows[fid]["name"], franchises) for fid in co)
            lines.append(
                f"| {season['season']} | {champ_cell} | — (co-champions) "
                f"| {cell(by_finish.get(3))} | — |"
            )
        else:
            champ = by_finish.get(1)
            lines.append(
                f"| {season['season']} "
                f"| {cell(champ)} "
                f"| {cell(by_finish.get(2))} "
                f"| {cell(by_finish.get(3))} "
                f"| {champ['record'] if champ else '—'} |"
            )
    return "\n".join(lines)


def records_table(seasons, franchises, overrides):
    lines = [
        "| Category | Holder | Value | Season |",
        "|:--|:--|:--|--:|",
    ]
    for r in compute_records(seasons, franchises, overrides):
        season = r["season"] if r["season"] is not None else "—"
        lines.append(f"| {r['category']} | {r['holder']} | {r['value']} | {season} |")
    return "\n".join(lines)


def main():
    franchises = load_franchises()
    seasons = load_seasons()
    overrides = load_overrides()

    content = f"""---
layout: page
title: League History
permalink: /history/
---
{GENERATED_NOTE}

## Champions

{champions_table(seasons, franchises, overrides)}

## Record Book

{records_table(seasons, franchises, overrides)}

*More records (highest-scoring week, biggest blowouts, head-to-head) unlock once
seasons have game-by-game scores added.*
"""

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content)
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
