#!/usr/bin/env python3
"""Generate docs/standings/index.md: final standings per season.

    .venv/bin/python scripts/generate_standings.py
"""

from pathlib import Path

from lib.data import load_franchises, load_seasons, owner_link
from lib.standings import get_standings, has_points
from lib.render import heat_chip

ROOT = Path(__file__).resolve().parent.parent
OUTPUT_PATH = ROOT / "docs" / "standings" / "index.md"

GENERATED_NOTE = "<!-- GENERATED by scripts/generate_standings.py — do not edit by hand. -->"


def season_table(season, franchises):
    rows = get_standings(season, franchises)
    points = has_points(rows)

    header = "| Finish | Team | Record |" + (" PF | PA |" if points else "")
    sep = "|:--|:--|:--|" + ("--:|--:|" if points else "")
    lines = [f"### {season['season']}", "", header, sep]

    pfs = [r["points_for"] for r in rows if r["points_for"] is not None]
    lo, hi = (min(pfs), max(pfs)) if pfs else (0, 0)

    for r in rows:
        team = owner_link(r["id"], r["name"], franchises)
        finish = f'<span class="star">★</span> {r["finish"]}' if r["finish"] == 1 else str(r["finish"])
        line = f"| {finish} | {team} | {r['record']} |"
        if points:
            pf = heat_chip(r["points_for"], lo, hi)
            line += f" {pf} | {r['points_against']} |"
        lines.append(line)
    return "\n".join(lines)


def main():
    franchises = load_franchises()
    seasons = load_seasons()

    body = "\n\n".join(season_table(s, franchises) for s in seasons)
    content = f"""---
layout: page
title: Standings
permalink: /standings/
---
{GENERATED_NOTE}

Final standings for each season, as recorded on ESPN (finish reflects playoff
results; the record shown is the regular season). Points columns appear once a
season has game-by-game scores added.

{body}
"""

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(content)
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
