#!/usr/bin/env python3
"""Import each season's ESPN scoring & roster settings into data/settings.yml.

This is the source-of-truth for the rulebook's "current settings" block and its
"Rule changes" log. Run it once a year (after any offseason rule changes) — see
scripts/refresh_rules.sh, which also rebuilds the site.

    .venv/bin/python scripts/import_settings.py            # seasons in data/seasons/
    .venv/bin/python scripts/import_settings.py 2008 2026  # a custom span

Cookies are read from `.espn-cookies` (private league). Stores RAW ESPN stat/slot
ids — labels are applied at build time by scripts/lib/rules.py, so fixing a label
never needs a re-import. Fetches only; writes just data/settings.yml.
"""

import os
import sys
from pathlib import Path

import yaml

try:
    from the_league_espn_api import League, ApiError
except ImportError:
    sys.exit("the-league-espn-api is not installed. Run: pip install -r requirements-dev.txt")

sys.path.insert(0, str(Path(__file__).resolve().parent))
from lib.rules import (scoring_map_from_settings, roster_map_from_settings,
                       format_from_settings)

ROOT = Path(__file__).resolve().parent.parent
SEASONS_DIR = ROOT / "data" / "seasons"
OUT_PATH = ROOT / "data" / "settings.yml"
COOKIES = os.environ.get("ESPN_COOKIES_FILE") or str(ROOT / ".espn-cookies")

HEADER = (
    "# ESPN scoring & roster settings, one entry per season. Generated by\n"
    "# scripts/import_settings.py — do not hand-edit. RAW ESPN stat/slot ids;\n"
    "# scripts/lib/rules.py labels them and diffs seasons into the rulebook's\n"
    "# 'Rule changes' log. Refresh once a year via scripts/refresh_rules.sh.\n"
)


def season_years():
    if SEASONS_DIR.is_dir():
        ys = sorted(int(p.stem) for p in SEASONS_DIR.glob("*.yml") if p.stem.isdigit())
        if ys:
            return ys
    return list(range(2010, 2027))


def fetch_one(year):
    settings = (League(year=year, cookies_file=COOKIES)
                .league_json("mSettings") or {}).get("settings", {})
    scoring = scoring_map_from_settings(settings)
    roster = roster_map_from_settings(settings)
    if not scoring and not roster:
        return None                       # nothing usable (very old / empty)
    return {
        "season": year,
        "format": format_from_settings(settings),
        # plain-int keys so the YAML is readable and stable
        "scoring": {int(k): v for k, v in sorted(scoring.items())},
        "roster": {int(k): v for k, v in sorted(roster.items())},
    }


def main():
    if len(sys.argv) == 3:
        years = list(range(int(sys.argv[1]), int(sys.argv[2]) + 1))
    else:
        years = season_years()

    entries = []
    for year in years:
        try:
            entry = fetch_one(year)
        except ApiError as e:
            print(f"NOTE: settings for {year} unavailable ({e}).", file=sys.stderr)
            continue
        if entry is None:
            print(f"NOTE: {year} returned no scoring/roster settings — skipped.",
                  file=sys.stderr)
            continue
        entries.append(entry)
        print(f"  {year}: {len(entry['scoring'])} scored stats, "
              f"{sum(entry['roster'].values())} roster spots, {entry['format']}")

    if not entries:
        sys.exit("No settings fetched — check cookies and network, nothing written.")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump({"seasons": entries}, sort_keys=False, allow_unicode=True,
                          default_flow_style=False)
    OUT_PATH.write_text(HEADER + "\n" + body, encoding="utf-8")
    print(f"\nWrote {OUT_PATH.relative_to(ROOT)} ({len(entries)} seasons). "
          f"Run scripts/build.py (or refresh_rules.sh) to update the rulebook.")


if __name__ == "__main__":
    main()
